defaultBranch: 'development'
branches:
  - label:
      - bug
      - enhancement
      - maintenance
      - todo
    name: development
    prefix: dev-
    prTarget: development
  - label:
      - documentation
    name: documentation
    prefix: doc-
    prTarget: documentation
branchName: '${issue.number}-${issue.title}'
openDraftPR: true
autoCloseIssue: true
