defaultBranch: 'development'
branches:
  - label:
      - bug
      - enhancement
      - good first issue
      - maintenance
      - todo
      - undefined behaviour
    name: development
    prefix: dev-
    prTarget: development
  - label:
      - documentation
      - help wanted
    name: documentation
    prefix: doc-
    prTarget: documentation
branchName: '${issue.number}-${issue.title}'
openDraftPR: true
autoCloseIssue: true
