defaultBranch: 'development'
branches:
  - label: 
      - documentation
      - help wanted
    name: documentation
    prefix: doc-
    prTarget: documentation
  - label: 
      - bug
      - enhancement
      - good first issue
      - maintenance
      - todo
      - undefined behaviour
    name: development
    prefix: dev-
    prTarget: development
branchName: 'issue-${issue.number}-${issue.title}'
openDraftPR: true
autoCloseIssue: true
