defaultBranch: 'development'
branches:
  - label: bug
    name: development
    prefix: dev_
  - label: documentation
    name: documentation
    prefix: doc_
branchName: '${issue.number}-${issue.title}'
autoCloseIssue: true
