defaultBranch: 'development'
branches:
  - label: documentation
    name: documentation
    prefix: doc-
    prTarget: documentation
  - label: bug
    name: development
    prefix: dev-
    prTarget: development
branchName: 'issue-${issue.number}-${issue.title}'
openDraftPR: true
autoCloseIssue: true
