defaultBranch: 'development'
branches:
  - label: bug
    name: development
    prefix: dev-
    prTarget: development
  - label: documentation
    name: documentation
    prefix: doc-
    prTarget: documentation
branchName: '${issue.number}-${issue.title}'
autoCloseIssue: true
