name: Set Issue Label

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened]

jobs:
  set-label:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: "both"
          parameters: '[ {"keywords": ["bug", "error", "fixme"], "labels": ["bug"], "assignees": [""]},
                         {"keywords": ["help", "guidance", "question"], "labels": ["help wanted"], "assignees": [""]},
                         {"keywords": ["documentation", "tutorial", "docs"], "labels": ["documentation"]}]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
